src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Experience_w_Media__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Experience w/ Media?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Storyteller_Notes__c</fullName>
        <label>Storyteller Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Team_Source__c</fullName>
        <description>This field tracks the Team(s) that acquired this contact. This field may be set by the Storybank App&apos;s create Contact functionality.</description>
        <label>Team Source</label>
        <picklist>
            <picklistValues>
                <fullName>Storybank</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

src/objects/Storybank_Submitted__c.object
<CustomObject>
    <fields>
        <fullName>Experience_w_Media__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Does the storyteller have experience interacting with the media?</inlineHelpText>
        <label>Experience w/ Media?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Storyteller_Notes__c</fullName>
        <label>Storyteller Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Source__c</fullName>
        <label>Team Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Storybank - Submitted</label>
    <nameField>
        <displayFormat>SBS-{000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Storybank - Submitted</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/StorybankFieldsStoryteller__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Used during the Storybank - Convert Submission process to INSERT/UPDATE a CONTACT record based on the data that was captured on the Storybank - Submitted object. This setting MAPS Storybank - Submitted fields to Contact fields based on the storyteller information that is populated on a Storybank - Submitted record.</description>
    <fields>
        <fullName>Contact_object_fieldname__c</fullName>
        <description>This field stores the API name of the Storybank - Submitted field that should be mapped to a Contact field as part of the Storybank Conversion process of the Storyteller&apos;s information.</description>
        <inlineHelpText>Storybank Submitted Field&apos;s API Name</inlineHelpText>
        <label>Storybank Submitted Storyteller Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_Order__c</fullName>
        <defaultValue>99</defaultValue>
        <inlineHelpText>Determine order fields displayed on update page</inlineHelpText>
        <label>Display Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Storybank Map Storyteller to Contact</label>
</CustomObject>

src/classes/TEST_StorybankContactUpdates.cls
@isTest
private with sharing class TEST_StorybankContactUpdates {
    
    @isTest
    private static void testUpdates_MVPFields () {
    
    TEST_DATA_Factory.setupStoryBankDefaults ();
    
    List<StorybankFieldsStoryteller__c> sb = new List<StorybankFieldsStoryteller__c> (); 
    sb.add(new StorybankFieldsStoryteller__c(Contact_object_fieldname__c='Team_Source__c', Name='Team_Source__c',Display_Order__c=999));
    sb.add(new StorybankFieldsStoryteller__c(Contact_object_fieldname__c='Experience_w_Media__c', Name='Experience_w_Media__c',Display_Order__c=999));
    sb.add(new StorybankFieldsStoryteller__c(Contact_object_fieldname__c='Storyteller_Notes__c', Name='Storyteller_Notes__c',Display_Order__c=999));
    insert sb;
    
    List<StorybankFieldsStoryteller__c> sfields = [Select Name, Contact_object_fieldname__c 
                                                FROM StorybankFieldsStoryteller__c WHERE Contact_object_fieldname__c != null
                                                Order By Display_Order__c ASC NULLS LAST, Name ASC ];

    Contact teststoryc = TEST_DATA_Factory.createExistingStoryteller();
    //Set a Team Source
    teststoryc.Team_Source__c = null;
    
    Storybank_Submitted__c testws1 = TEST_DATA_Factory.createselfsubmission();
    testws1.Team_Source__c = null;
    
        List<StorybankContactUpdates> contactFieldUpdates = new List<StorybankContactUpdates> ();
        for (StorybankFieldsStoryteller__c s: sFields) {
            contactFieldUpdates.add( new StorybankContactUpdates(s.name, s.Contact_object_fieldname__c,testws1, teststoryc));
        }

        system.assertequals(null,teststoryc.Team_Source__c);
        system.assertequals(FALSE,teststoryc.Experience_w_Media__c);
        

        teststoryc = StorybankContactUpdates.setValuesonContact (teststoryc, testws1, contactFieldUpdates);
        system.assertequals(null,teststoryc.Team_Source__c);
        system.assertequals(TRUE,teststoryc.Experience_w_Media__c);
    

        teststoryc.Team_Source__c = 'Story 2';
    
        contactFieldUpdates = new List<StorybankContactUpdates> ();
        for (StorybankFieldsStoryteller__c s: sFields) {
            contactFieldUpdates.add( new StorybankContactUpdates(s.name, s.Contact_object_fieldname__c, testws1, teststoryc));
        }

        system.assertequals('Story 2',teststoryc.Team_Source__c);
        teststoryc = StorybankContactUpdates.setValuesonContact (teststoryc, testws1, contactFieldUpdates);
        system.assertequals('Story 2',teststoryc.Team_Source__c);

        testws1.Team_Source__c = 'Story 4';
    
        contactFieldUpdates = new List<StorybankContactUpdates> ();
        for (StorybankFieldsStoryteller__c s: sFields) {
            contactFieldUpdates.add( new StorybankContactUpdates(s.name, s.Contact_object_fieldname__c, testws1, teststoryc));
        }

        system.assertequals('Story 2',teststoryc.Team_Source__c);
        teststoryc = StorybankContactUpdates.setValuesonContact (teststoryc, testws1, contactFieldUpdates);
        system.assertequals('Story 2;Story 4',teststoryc.Team_Source__c);

        teststoryc.Team_Source__c = null;
        teststoryc.Storyteller_Notes__c = 'Test New Line';

        contactFieldUpdates = new List<StorybankContactUpdates> ();
        for (StorybankFieldsStoryteller__c s: sFields) {
            contactFieldUpdates.add( new StorybankContactUpdates(s.name, s.Contact_object_fieldname__c, testws1, teststoryc));
        }
        
        system.assertequals(null,teststoryc.Team_Source__c);
        system.assertequals('Test New Line' , teststoryc.Storyteller_Notes__c);
        
        teststoryc = StorybankContactUpdates.setValuesonContact (teststoryc, testws1, contactFieldUpdates);
        
        system.assertequals('Story 4',teststoryc.Team_Source__c);
        system.assertequals('Test New Line'  + '\n\n' + 'Test Notes + Test More Notes', teststoryc.Storyteller_Notes__c);
        
        //Text Area for Street
        testws1.Street_Address__c = 'Test Street 1';
        system.assertequals(null,teststoryc.MailingStreet);

        contactFieldUpdates = new List<StorybankContactUpdates> ();
        for (StorybankFieldsStoryteller__c s: sFields) {
            contactFieldUpdates.add( new StorybankContactUpdates(s.name, s.Contact_object_fieldname__c,testws1, teststoryc));
        }
        teststoryc = StorybankContactUpdates.setValuesonContact (teststoryc, testws1, contactFieldUpdates);
        system.assertequals('Test Street 1',teststoryc.MailingStreet);

        testws1.Street_Address__c = 'Test Street 2';
        
        contactFieldUpdates = new List<StorybankContactUpdates> ();
        for (StorybankFieldsStoryteller__c s: sFields) {
            contactFieldUpdates.add( new StorybankContactUpdates(s.name, s.Contact_object_fieldname__c, testws1, teststoryc));
        }
         teststoryc = StorybankContactUpdates.setValuesonContact (teststoryc, testws1, contactFieldUpdates);
        system.assertequals('Test Street 2',teststoryc.MailingStreet);


    }
}