src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age_Range__c</fullName>
        <label>Age Range</label>
        <picklist>
            <picklistValues>
                <fullName>13-18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19-34</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>35-64</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>65+</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Disability__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disability</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Other Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Experience_w_Media__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Experience w/ Media?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rather not say</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Storyteller_Notes__c</fullName>
        <label>Storyteller Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Team_Source__c</fullName>
        <description>This field tracks the Team(s) that acquired this contact. This field may be set by the Storybank App&apos;s create Contact functionality.</description>
        <label>Team Source</label>
        <picklist>
            <picklistValues>
                <fullName>Storybank</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Veteran__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Veteran</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Storybank_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Used to setup org specific default values for the Storybank application.</description>
    <fields>
        <fullName>Target_Value__c</fullName>
        <label>Target Value</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Storybank Settings</label>
</CustomObject>

src/objects/Storybank_Submitted__c.object
<CustomObject>
    <fields>
        <fullName>Age_range__c</fullName>
        <label>Age Range</label>
        <picklist>
            <picklistValues>
                <fullName>13-18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19-34</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>35-64</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>65+</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Agree_to_Terms_of_Use__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Agree to Terms of Use</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Attribution__c</fullName>
        <inlineHelpText>How submitter wants to be known...</inlineHelpText>
        <label>Pseudonym</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Category Chosen by Submitter</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing and Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Disability__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disability</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <inlineHelpText>Email address of Submitter</inlineHelpText>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Embed_URL__c</fullName>
        <label>Embed URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Other Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Experience_w_Media__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Does the storyteller have experience interacting with the media?</inlineHelpText>
        <label>Experience w/ Media?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Final_Copy__c</fullName>
        <label>Final Copy</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <inlineHelpText>First Name of Submitter</inlineHelpText>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rather Not Say</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <inlineHelpText>Last Name of Submitter</inlineHelpText>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nominator_City__c</fullName>
        <label>Nominator City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nominator_Email_Address__c</fullName>
        <label>Nominator Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Nominator_Last_Name__c</fullName>
        <label>Nominator Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Category__c</fullName>
        <label>Other Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_pick__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Storyteller_Notes__c</fullName>
        <label>Storyteller Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Submission_Type__c</fullName>
        <label>Submission Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team_Source__c</fullName>
        <label>Team Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Veteran__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Veteran</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Video_URL__c</fullName>
        <inlineHelpText>URL of Video being submitted</inlineHelpText>
        <label>Video URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Video__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Video</label>
        <type>Checkbox</type>
    </fields>
    <label>Storybank - Submitted</label>
    <nameField>
        <displayFormat>SBS-{000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Storybank - Submitted</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TEST_DATA_Factory.cls
public class TEST_DATA_Factory {


public static void setupStoryBankDefaults () {

    Account a = new Account (Name = 'Default SB Account');
    insert a;

    CollaborationGroup cg = new CollaborationGroup(Name = 'Test Group' + string.valueof(system.today()), CollaborationType = 'Public' );
    insert cg;

    List<Storybank_Settings__c> sbtest = new List<Storybank_Settings__c> ();
        
    sbtest.add(new Storybank_Settings__c (Name = 'DefaultAccountId', target_value__c = a.Id ));
    sbtest.add(new Storybank_Settings__c (Name = 'ChatterGroupId', target_value__c = cg.Id ));
    sbtest.add(new Storybank_Settings__c (Name = 'NominatorRecordTypeId'));
    sbtest.add(new Storybank_Settings__c (Name = 'StorytellerRecordTypeId'));
    sbtest.add(new Storybank_Settings__c (Name = 'NominatorOrgRecordTypeId'));
        
    insert sbtest;
    
    StorybankInstallationScripts.setupNominatorSettings();
    StorybankInstallationScripts.setupStoryTellerSettings();
    StorybankInstallationScripts.setupNominatorOrgSettings();
    StorybankInstallationScripts.setupApprovedStorybankSettings();

    }
 
public static Storybank_Submitted__c createselfsubmission() {

    Storybank_Submitted__c ws = new Storybank_Submitted__c();

    ws.Submission_Type__c = 'Submitted by Self';
    ws.Agree_to_Terms_of_Use__c = TRUE;
    ws.First_Name__c = 'TestF';
    ws.Last_Name__c = 'TestL';
    ws.Email_Address__c = 'testselfnew@bfcclient.com';
    ws.City__c = 'Washington';
    ws.State_pick__c = 'DC';
    ws.Postal_Code__c = '20005';
    ws.Gender__c = 'Male';
    ws.Ethnicity__c = 'White';
    ws.Veteran__c = FALSE;
    ws.Age_range__c = '35-64';
    ws.Disability__c = FALSE;
    ws.Storyteller_Notes__c = 'Test Notes + Test More Notes';
    ws.Experience_w_Media__c = TRUE;
    ws.Category__c='Education';
    ws.Attribution__c=null;
    ws.Final_Copy__c='Test Final Copy'; 
    ws.Team_Source__c = 'Story 2';
    ws.Video_URL__c=null; 
    ws.Video__c=FALSE; 
    ws.Embed_URL__c=null; 
    ws.Other_Category__c=null;
    
    return ws;

 }  


public static Storybank_Submitted__c createnominatorsubmission() {

    Storybank_Submitted__c ws = createselfsubmission();

    ws.Submission_Type__c = 'Submitted by Nominator';
    ws.Nominator_Last_Name__c = 'TestNL';
    ws.Nominator_Email_Address__c = 'testnom@bfcclient.com';
    ws.Nominator_City__c = 'Nom City';
    ws.Nominator_State_pick__c = 'VA';
    ws.Nominator_Postal_Code__c = '22206';
    ws.Nominator_Notes__c = ' Nominator Notes';
    ws.Nominator_Organization__c = 'Test NOM Org';
    ws.Nominator_Phone__c = '202-555-1234';
    
    return ws;


}  

public static Contact createExistingStoryteller() {

    Contact c = new Contact();
    c.AccountId = Storybank_Settings__c.getValues('DefaultAccountId').Target_Value__c;
    c.LastName = 'StoryL';
    c.FirstName = 'StoryF';
    c.Email = 'story1@bfcclient.com';

    return c;
}  


public static Account createExistingNominatorOrg() {

    Account a = new Account();
    a.Name = 'Story1';

    return a;
}  


public static Contact createExistingNominatorContact() {

    Account a = createExistingNominatorOrg();
    insert a;

    Contact c = new Contact();
    c.AccountId = a.Id;
    c.LastName = 'NomL';
    c.FirstName = 'NomF';
    c.Email = 'nom1@bfcclient.com';

    return c;


}  

}