src/objects/Storybank_Submitted__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Category Chosen by Submitter</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing and Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Submission_URL__c</fullName>
        <inlineHelpText>URL this story was submitted from - then we can set certain defaults</inlineHelpText>
        <label>Submission URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Storybank - Submitted</label>
    <nameField>
        <displayFormat>SBS-{000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Storybank - Submitted</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PublicStorybankSubmissionController.cls
global with sharing class PublicStorybankSubmissionController {
/* 
Class to control public facing web page for Storybank
The class is declared as Global so that customers can clone the included page and use their own
to capture stories
*/

private Storybank_Submitted__c newws;
global List<wcategory> publiccategories {get;set;}


global PublicStorybankSubmissionController() {
 
    newws = new Storybank_Submitted__c(); 
    newws.Submission_URL__c = ApexPages.currentPage().geturl();
 
    publiccategories = new List<wcategory> ();
    Schema.DescribeFieldResult fieldResultd = Storybank_Submitted__c.category__c.getDescribe();
    List<Schema.PicklistEntry> pled = fieldResultd.getPicklistValues();
    for (Schema.PicklistEntry f : pled)   {
        publiccategories.add(new wcategory(f.getValue()));
    }    
}

global Storybank_Submitted__c getnewws() {
    return newws;
}

 global PageReference submit() {

    newws.Category__c = '';
    for (wcategory w: publiccategories) {
        if (w.bselected) {
            newws.Category__c += w.sCategory + ';';
        }
    }

    try {
        upsert newws;
        return page.StorybankSubmissionConfirmation;
    }
    Catch (Exception Ex) {
        return null;
    } 

} //end submit 

global class wcategory {

    global boolean bselected {get;set;}
    global string sCategory {get;set;}

    global wcategory(String scat) {
        sCategory = scat;
        bselected = false;
    }
}

}